name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter codigo do projeto
        uses: actions/checkout@v4
      - name: Construir Imagem Docker
        run: echo "Executando docker build"
      - name: Envio da Imagem
        run: echo "Executando docker push"
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Auntenticar na AWS
        run: echo "Executando aws configure"
      - name: Configurar o kubectl
        run: echo "Executando docker build"
      - name: Envio da Imagem
        run: echo "Executando docker push"
